name: Generate commit message

on:
  pull_request:
    types: [opened, edited]

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Generate commit message
        uses: peter-evans/commit-comment@v3
        with:
          commit-message-file: commit-message.txt
      - name: Commit changes
        run: |
          git add .
          git config --global user.email "amasiye313@gmail.com"
          git config --global user.name "Andrew Masiye"
          git commit -F commit-message.txt
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
